### ISSUE TITLE
Cannot find module 'babel-polyfill'

### ISSUE THREAD

**Issue by adius** [datatypesjs/moment#10]
Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/adrian/Projects/things/node_modules/@datatypes/moment/build/classes/Instant.js:9:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by adius** [comment]
Duplicate
